#### python libraries

### Numpy

In [4]:
#### create 1D array
import numpy
x=numpy.array([1,2,3,4])
print(x)

[1 2 3 4]


In [1]:
import numpy
x=typeof([1,2,3,4])
print(x)

NameError: name 'typeof' is not defined

In [2]:
type(x)

NameError: name 'x' is not defined

In [3]:
import numpy
x=numpy.array([1,2,3,4])
print(x)

[1 2 3 4]


In [4]:
print(type(x))

<class 'numpy.ndarray'>


In [2]:
import numpy
y=numpy.array([[1,2,3,4],[5,6,7,8]])
print(y)

[[1 2 3 4]
 [5 6 7 8]]


In [3]:
import numpy
z=numpy.array([[[1,2,3,4],[5,6,7,8],[9,1,2,3]]])
print(z)

[[[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]]


In [3]:
import numpy
z=numpy.array([[[1,2,3,4],[5,6,7,8],[9,1,2,3]]])
print(z)
z.size

[[[1 2 3 4]
  [5 6 7 8]
  [9 1 2 3]]]


12

In [9]:
import numpy as np
a=([1,2],[3,4],[5,6])
s=np.array([1,2,3,4,5,6], dtype=complex)
print(s)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j]


# array slicing

In [11]:
import numpy 
k=numpy.arange(100)
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [12]:
k[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
k[::2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
k[::3]

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [15]:
k[5::]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
       56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72,
       73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
       90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [16]:
k[0:56:33]

array([ 0, 33])

In [17]:
k[2:10:3]

array([2, 5, 8])

In [18]:
k[2::4]

array([ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38, 42, 46, 50, 54, 58, 62, 66,
       70, 74, 78, 82, 86, 90, 94, 98])

In [19]:
k[-1::]

array([99])

In [20]:
k[::-1]

array([99, 98, 97, 96, 95, 94, 93, 92, 91, 90, 89, 88, 87, 86, 85, 84, 83,
       82, 81, 80, 79, 78, 77, 76, 75, 74, 73, 72, 71, 70, 69, 68, 67, 66,
       65, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49,
       48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [26]:
import numpy
k=numpy.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[4,5,6,8]]])
print(k)

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [4 5 6 8]]]


In [32]:
import numpy
k=numpy.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[4,5,6,8]]])
print(k)
k.size
k.shape
k.ndim

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [4 5 6 8]]]


3

In [36]:
import numpy
k=numpy.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[4,5,6,8]]])
print(k)
k.size
k.shape
k.ndim


[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [4 5 6 8]]]


3

In [41]:
r=np.arange(1,17).reshape(4,4)
print(r)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [42]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate([x,y])
print(z)

[1 2 3 4 5 6]


In [47]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=[x+y]
print(z)


[array([5, 7, 9])]


#### splitting of arrays

In [48]:
x=[1,2,3,4,5,6,9,8]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [4 5] [6 9 8]


In [52]:
v=np.arange(1,16).reshape(5,3)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [53]:
a4=np.arange(12).reshape(2,6)
print(a4)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [54]:
a1=np.ones((3,3))
print(a1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [56]:
a2=np.zeros((7,3))
print(a2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [65]:
import numpy as np
a3=[1,2,3]
a5=np.array(a3)
print(np.sqrt(a5))
print(np.sin(a5))
print(np.cos(a5))
print(np.tan(a5))


[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[ 1.55740772 -2.18503986 -0.14254654]


In [67]:
x1=np.random.randint(5,size=15)
print(x1)

[1 1 3 4 0 4 4 1 0 3 3 2 0 4 0]


In [71]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__file__', '__getattr__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytes

In [72]:
print(len(dir(np)))

620


In [74]:
print(np.__version__)

1.19.2


In [73]:
print(np.__version__)

1.19.2


In [ ]:
import nump as np
d=np.array[1,2,3]
x=[true,false]